---
- volumes: {}
  static_ips: {}
  vpc:
    id: vpc-2727fb43
    instance_subnets:
      public:
      - availability_zone: us-east-1b
        subnet_id: subnet-7f302e08
        cidr: 10.0.0.0/24
      private:
      - availability_zone: us-east-1b
        subnet_id: subnet-402d3337
        cidr: 10.0.1.0/24
