---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: nat
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nat_gateway
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-1c67aec8
  image_type: c1.medium
  image_id: ami-92f569fa
  security_groups:
  - rubber_test_production_default
  zone: us-east-1b
  gateway: public
  external_host: 
  external_ip: 54.152.140.163
  internal_host: ip-10-0-0-251.ec2.internal
  internal_ip: 10.0.0.251
  provider: aws
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-4c0ac298
  image_type: c1.medium
  image_id: ami-92f569fa
  security_groups:
  - rubber_test_production_default
  zone: us-east-1b
  gateway: i-1c67aec8
  external_host: 
  external_ip: 
  internal_host: ip-10-0-1-225.ec2.internal
  internal_ip: 10.0.1.225
  provider: aws
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-e836fe3c
  image_type: c1.medium
  image_id: ami-92f569fa
  security_groups:
  - rubber_test_production_default
  zone: us-east-1b
  gateway: i-1c67aec8
  external_host: 
  external_ip: 
  internal_host: ip-10-0-1-31.ec2.internal
  internal_ip: 10.0.1.31
  provider: aws
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-5f7db58b
  image_type: c1.medium
  image_id: ami-92f569fa
  security_groups:
  - rubber_test_production_default
  - rubber_test_production_web
  zone: us-east-1b
  gateway: public
  external_host: 
  external_ip: 54.210.229.103
  internal_host: ip-10-0-0-141.ec2.internal
  internal_ip: 10.0.0.141
  provider: aws
  platform: linux
  root_device_type: instance-store
  network: rubber_test_production
- volumes: {}
  static_ips: {}
  vpc: {}
